In [ ]:
fun: 56712.08203125
       message: 'Optimization terminated successfully.'
          nfev: 1286
           nit: 414
        status: 0
       success: True
             x: array([2.17507271e-01, 6.68290234e-02, 6.02503642e-03, 3.11701327e+04,
       1.50929989e+02, 1.80605742e+02, 4.19481041e+03])

In [ ]:
import pyro
import torch
from torch import tensor
from pyro.distributions import Dirichlet, Beta, DirichletMultinomial as DM, Multinomial, LogNormal, Gamma

In [ ]:
torch.lgamma(1 + tensor(2.0,dtype=torch.double))

In [ ]:
Dirichlet(is_sparse=True, concentration=tensor([ 6.94358849e+03,
       3.42261484e+02, 2.88434875e+02, 3.43087928e+04], dtype=torch.double)).log_prob(tensor(.5))

In [ ]:
Dirichlet(tensor([5.13379907e+03,
       4.73718801e+03, 4.48497620e+03, 3.15466320e+04])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([3.27633494e+04,
       2.83978623e+02, 2.71735494e+02, 7.29106887e+03])).sample([10_000,]).mean(0)

In [ ]:
Dirichlet(tensor([1.11277492e+04,
       4.78012719e+03, 4.69497849e+03, 2.55812574e+04])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([1.75637015e+04,
       2.81087516e+03, 3.07357980e+03, 5.10828082e+03])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([3.67968382e+04,
       4.71664044e+03, 1.34100715e+03, 6.33673565e+02])).sample([10_000]).mean(0)

In [ ]:
alphas = tensor([0.4156, 0.0056, 0.0047, 0.5742])
alpha1= alphas[1]


Beta(alpha1, alphas.sum() - alpha1).sample([10_000, ]).mean()

In [ ]:
Dirichlet(tensor([tensor(17716.9375), tensor(18139.4492), tensor(19317.7422), tensor(12943.7344)])).sample([10_000,]).mean(0)

In [ ]:
Dirichlet(tensor([2.30539340e+04,
       2.62614394e+03, 2.47748207e+03, 3.03769349e+03])).sample([10_000,]).mean(0)

In [ ]:
Dirichlet(tensor([1.59403035e+04,
       2.26238457e+03, 1.40300754e+03, 9.03945767e+03])).sample([10_000,]).mean(0)


In [ ]:
Dirichlet(tensor([ 1.94390627e+01,
       1.99240417e+00, 2.07841816e+00, 2.53949348e+00])).sample([10_000,]).mean(0)

In [ ]:
Dirichlet(tensor([1.67319273e+04,
       8.27414401e+03, 6.84802281e+03, 2.71042895e+04])).sample([10_000,]).mean(0)

In [ ]:
# best of genData2 + function idx 3
# pis: 7.02865381e-02, 1.06889511e-01, 5.09662635e-02
# this is actually fucking close; .07, .1 and .05
Dirichlet(tensor([3.70873017e+04,
       7.73578433e+03, 8.70734635e+03, 4.40364835e+03])).sample([10_000,]).mean(0)

In [ ]:
0.0790 * (.1/(.1 + .05)) + .3156 * (.05/(.1 + .05))

In [ ]:
def pVgivenD(rr, pV):
    return (rr * pV) / (rr * pV + (1 - pV))

# pD: prevalence, tensor of mConditions x 1
# pVgivenD: tensor of mConditions x 1
# pV: allele frequency
def pVgivenNotD(pD, pV, pVgivenD):
    p = (pV - (pD*pVgivenD).sum()) / (1 - pD.sum())
    assert(p >= 0)
    return p

# def pVgivenNotD(pD, pV, pVgivenD):
#     p = (pV - (pD*pVgivenD)) / (1 - pD)
#     assert(p >= 0)
#     return p

def pDgivenV(pD, pVgivenD, pV):
    return pVgivenD * pD / pV

In [ ]:
P(V) = P(V|D1)P(D1) + P(V|D2)P(D2) + P(V|DBoth)P(DBoth)

In [ ]:
P(D) = P(D1|V)P(V) + P(D2|V)P(V) + P(DBoth|V)P(V)

In [ ]:
rr = P(D|V) / P(D|!V)

In [ ]:
P(D|V) = P(D1|V) + P(D2|V) + P(DBoth|V)

In [ ]:
Dirichlet(tensor([3.09019048e+04,
       4.19213154e+03, 4.21335767e+03, 4.26188535e+03])).sample([10_000]).mean(0)


In [ ]:
Dirichlet(tensor([1.80304463e+04,
       4.22627298e+03, 4.08179035e+03, 2.08259009e+03])).sample([10_000,]).mean(0)

In [ ]:
Dirichlet(tensor([3.89260152e+04,
       6.21964619e+03, 6.44190860e+03, 3.01255992e+03])).sample([10_000]).mean(0)


In [ ]:
DirichletMultinomial(tensor[10e4, 1e3, 1e3, 1e3])

In [ ]:
# torch.exp( DirichletMultinomial(total_count=n, concentration=tensor([alpha0, alpha1, alpha2, alphaBoth])).log_prob(altCountsFlat) )
def oneProbDMN(n, alphas, counts):
    return torch.exp( DirichletMultinomial(total_count=n, concentration=alphas).log_prob(counts) )

def oneProbMN(n, probs, counts):
    return torch.exp( Multinomial(total_count=n, probs=tensor(probs)).log_prob(tensor(counts)) )

In [ ]:
sharedCount = 2.
iCount1 = 1.
iCount2 = 1.

# in shared genes
sample1Count = iCount1 + sharedCount
sample2Count = iCount2 + sharedCount
sampleBothCount = iCount1 + iCount2 + sharedCount
oneProbMN(4., [.1,.1,.1], [1.,1.])

In [ ]:
DirichletMultinomial?

In [ ]:
Dirichlet(tensor([1.54761107e+01,
       6.02123698e-01, 1.21507139e+00, 1.54442097e-04])).sample([10_000,]).mean(0)

In [ ]:
Dirichlet(tensor([18.3388,  1.8321,  0.5886,  0.0941])).sample([10_000,]).mean(0)

In [ ]:
Dirichlet(tensor([34300.5433,  3441.8291,  1440.9554,   127.5581])).sample([10_000,]).mean(0)

In [ ]:
marginal = tensor([1., 2., 0, 3])


In [ ]:
marginal.sum()

In [ ]:
torch.exp(Multinomial(probs=tensor([0.01, 0.01, 0.01, 0.01])).log_prob(marginal))

In [ ]:
Dirichlet(tensor([1.67153400e+04,
       1.18286093e+03, 1.40517890e+03, 1.44319379e+03])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([2.59400775e+04,
       2.47609775e+03, 2.29825512e+03, 3.59544889e+02])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([2.33948260e+04,
       1.41297532e+03, 1.46910198e+03, 1.56015665e+02])).sample([10_000]).mean(0)

In [ ]:
# genData4, likelihood2i, epoch 1
Dirichlet(tensor([2.11498113e+04,
       3.32979065e+03, 3.31985949e+03, 3.88146710e+03])).sample([10_000]).mean(0)

# genData4, likelihood2i ,epoch 2
Dirichlet(tensor([5.70757138e+01,
       8.66106939e+00, 8.56601513e+00, 1.01019871e+01])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([2.46362341e+04,
       3.87863391e+03, 3.86748009e+03, 4.52212702e+03])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([5.70061092e+01,
       8.63865940e+00, 8.57262742e+00, 1.00505577e+01])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([4.93612217e+04,
       6.23437490e+03, 6.17674668e+03, 3.64023421e+03])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([2.27326493e+04,
       2.87094354e+03, 2.84417493e+03, 1.67617095e+03])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([3.10033120e+04,
       3.91561327e+03, 3.87910403e+03, 2.28663592e+03])).sample([10_000]).mean(0)

In [ ]:
t = tensor([0,1,22,31,40,52,6,7,8,91,10])

In [ ]:
t[-tensor([0,3,10])]

In [ ]:
def pVgivenD(rr, pV):
    return (rr * pV) / (rr * pV + (1 - pV))

# pD: prevalence, tensor of mConditions x 1
# pVgivenD: tensor of mConditions x 1
# pV: allele frequency
def pVgivenNotD(pD, pV, pVgivenD):
    p = (pV - (pD*pVgivenD).sum()) / (1 - pD.sum())
    if(p < 0):
        raise ValueError(f"pVgivenNotD: invalid params: pD: {pD}, pV: {pV}, pVgivenD: {pVgivenD} yield: p = {p}")
    return p

# def pVgivenNotD(pD, pV, pVgivenD):
#     p = (pV - (pD*pVgivenD)) / (1 - pD)
#     assert(p >= 0)
#     return p

def pDgivenV(pD, pVgivenD, pV):
    return pVgivenD * pD / pV



In [ ]:
rr = 10
pV = 1e-4

pvgivend = pVgivenD(rr, pV)
print(pvgivend)
pDgivenV(pD = .01, pVgivenD = pvgivend, pV=pV)

In [ ]:
DM(tensor([7.86794799e+02,
       9.71017825e+03, 9.99508241e+03, 1.14765185e+04])).sample([10_000]).mean(0)

In [ ]:
0.0216 * .8

In [ ]:
.66 * 0.3048 * .1 + .33 * .1 * (0.3048 + 0.3567)

In [ ]:
# 2M round 1 final number:
DM(tensor([0.7389, 0.7504, 0.1959])).sample([10_000]).mean(0)

In [ ]:
# Samples1
.66 * .1 * .7389 + .33 * .1 * (0.7389 + 0.1959)

In [ ]:
DirichletMultinomial?

In [ ]:
# best 2 params for round 1 of rr = 5, rr = 5 , rr = 2 and model 2l
DM(tensor([2.73908616e+04,
       1.59702502e+03, 1.69733393e+03, 4.46021382e+02])).sample([10_000,]).mean(0)

DM(tensor([4.38209361e+02,
       2.46545176e+01, 2.63717375e+01, 7.22616621e+00])).sample([10_000,]).mean(0)

In [ ]:
# 2 best for rr = 3, rr = 3 , rr = 1.5 and model 2l
DM(tensor([1.00697359e+03,
       3.61357400e+01, 3.75683988e+01, 9.63759760e+00])).sample([10_000,]).mean(0)

In [ ]:
DM(tensor([5.87372505e+03,
       2.13632552e+04, 2.11317348e+04, 9.39869442e+03])).sample([10_000,]).mean(0)

In [ ]:
DM(tensor([6.08863291e+02,
       2.08288623e+01, 2.08965160e+01, 6.25787127e+00])).sample([10_000,]).mean(0)

In [ ]:
DM(tensor([2.73667035e+04,
       1.41288604e+03, 1.12626550e+03, 1.68162263e-03])).sample([10_000,]).mean(0)

In [ ]:
DM(tensor([3.70329944e+02,
       1.02952233e+01, 1.11533395e+01, 2.44187071e+00])).sample([10_000,]).mean(0)

In [ ]:
DM(tensor([2.39872919e+04,
       8.93246165e+02, 8.55821572e+02, 9.28781215e+01])).sample([10_000,]).mean(0)

In [ ]:
DM?

In [ ]:
DM(tensor([1.84832811e+04,
       2.27506360e+03, 2.18035721e+03, 4.17154933e+02])).sample([10_000,]).mean(0)

In [ ]:
#best epoch of rr 5 rr 5 rr 2 fractions .05 .05 .05 likelihood2l, first run
DM(tensor([4.43312407e+02,
       2.52019987e+01, 2.54726471e+01, 2.55182419e+00])).sample([10_000,]).mean(0)

In [ ]:
#2nd run
DM(tensor([1.34015028e+04,
       8.00831023e+02, 8.28118710e+02, 6.14283168e+01])).sample([10_000,]).mean(0)

In [ ]:
from scipy.stats import truncnorm
import torch


def truncated_normal(size, threshold=1):
    values = truncnorm.rvs(-threshold, threshold, size=size)
    return values

# usage example
x= truncnorm([10, 20], threshold=1)   # sample 10x20 sized tensor
x = torch.from_numpy(x).cuda()

In [ ]:
truncnorm?

In [ ]:
mean = tensor([3.,2.])
cov = tensor([[1., .9],[.9,1.]])

from torch.distributions import MultivariateNormal
mvn = MultivariateNormal(mean, cov)

In [ ]:
test = mvn.sample([1000])
test

In [ ]:
testOne = MultivariateNormal(loc=tensor([5., 5.]), covariance_matrix=tensor([[1., 0.],[0., 1]])).sample([20_000])
testOne

In [ ]:
np.corrcoef(testOne[:, 0], testOne[:, 1])

In [ ]:
test = MultivariateNormal(loc=tensor([7., 7., 12.]), covariance_matrix=tensor([[1., 0.9, 0.9],[0.9, 1, 0.9], [0.9, 0.9, 1.]])).sample([20])

In [ ]:
test

In [ ]:
print("1", test[:, 0].min())
print("1", test[:, 1])



In [ ]:
torch.exp

In [ ]:
np.corrcoef(test[:, 0], test[:, 1])

In [ ]:
m = LogNormal(torch.tensor([0.0]), torch.tensor([1.0]))
m.sample([10_000])

In [ ]:
import numpy as np

In [ ]:
np.corrcoef(test)

In [ ]:
from scipy import stats

In [ ]:
x = stats.multivariate_normal.cdf(test, mean, cov)
x

In [ ]:
Multinomial.cdf(value=x)

In [ ]:
Dirichlet(tensor([6.37228665e+05,
       3.94523352e+04, 3.58150096e+04, 4.00801714e+03])).sample([10_000]).mean(0)

In [ ]:
Multinomial?

In [ ]:
Dirichlet(tensor([3.45767546e+02,
       2.02085162e+01, 1.89984386e+01, 2.06313145e+00])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([4.58943594e+02,
       1.62079432e+01, 1.39259322e+01, 1.74798837e+00])).sample([10_000]).mean(0)

In [ ]:
#P(V|D)P(D) = P(D|V)P(V) or P(V|D)P(D) ~ P(D|V)

In [ ]:
Dirichlet(tensor([2.62689297e+02,
       1.46873198e+03, 1.28028588e+03, 9.60504829e+02])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([1070.0174, 6370.6853, 5331.2606, 3840.4440])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([4.85336455e+03,
       2.50057173e+04, 2.79659395e+04, 1.49752803e+04])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([2.63195506e+03,
       2.99568070e+02, 3.03870925e+02, 2.64435039e+01])).sample([10_000]).mean(0)

In [ ]:
Dirichlet(tensor([2.63195506e+03,2.99568070e+02, 3.03870925e+02, 2.64435039e+01])).sample([10_000]).mean(0)

In [ ]:
pds = tensor([0.9785, 0.0098, 0.0098, 0.0020])
alphas = tensor([1.84813348e+03, 2.09636601e+04, 2.13425518e+04, 9.79171130e+03])
print("P(D|V) inferred in first component is:", Dirichlet(tensor([alphas[0], alphas[1], alphas[0], alphas[2]]) * pds).sample([10_000]).mean(0))
print("P(D|V) inferred in first component is:", Dirichlet(tensor([alphas[0], (alphas[1] + alphas[3]), (alphas[2] + alphas[3]), (alphas[1] + alphas[2] + alphas[3])]) * pds).sample([10_000]).mean(0))


In [ ]:
r = MultivariateNormal(tensor([5, 5, 2.]), tensor([[1,0, 0.], [0, 1, 0], [0, 0, 1]])).sample([10_000])
r.mean(0)

In [ ]:
x = Gamma(50, 50/2).sample([10_000])

In [ ]:
x.std()

In [ ]:
# first run
# res = tensor([6.02019095e-03, 1.67553253e-02, 9.74496445e-03, 7.69605932e+03,
#        1.69769687e+04, 1.27275565e+04, 1.37402223e+04])
# best run
res = tensor([1.95625714e-03, 4.34741045e-03, 7.93597145e-03, 9.49925716e+03,
       2.27481847e+04, 1.94932489e+04, 1.71843974e+04])
inferredPis = res[0:3]
inferredAlphas = res[3:]
pDsRun = tensor([0.0280, 0.0280, 0.0112])

In [ ]:
from mvl import genData, likelihoods

rrsSimRun = tensor([1.5, 1.5, 1.5])
pisSimRun = tensor([.01, .01, .01])
nCases = tensor([15e3, 15e3, 6e3])
nCtrls = tensor(5e5)
afMeanRun = 1e-4

paramsRun = genData.genParams(rrMeans=rrsSimRun, pis=pisSimRun, afMean=afMeanRun, rrShape=tensor(50.), afShape=tensor(50.), nCases=nCases, nCtrls=nCtrls)[0]

pDsRun = paramsRun["pDs"]
pisRun = paramsRun["diseaseFractions"]
print("params are:", paramsRun)

generatingFn = genData.v6

resPointer = generatingFn(**paramsRun)

afsRun = resPointer["afs"]
xsRun = resPointer["altCounts"]
afsRun = resPointer["afs"]
affectedGenesRun = resPointer["affectedGenes"]
unaffectedGenesRun = resPointer["unaffectedGenes"]

                
component1Afs = afsRun[affectedGenesRun[0]]
afMeanRun 
c1true = (component1Afs / afMeanRun).mean(0)

component2Afs = afsRun[affectedGenesRun[1]]
c2true = (component2Afs / afMeanRun).mean(0)

componentBothAfs = afsRun[affectedGenesRun[2]]
cBothTrue = (componentBothAfs / afMeanRun).mean(0)

In [ ]:
pds = tensor([1-pDsRun.sum(), *pDsRun])
alphas = inferredAlphas.numpy()
c1inferred = Dirichlet(tensor([alphas[0], alphas[1], alphas[0], alphas[2]]) * pds).sample([10_000]).mean(0)
c2inferred = Dirichlet(tensor([alphas[0], alphas[0], alphas[2], alphas[2]]) * pds).sample([10_000]).mean(0)
cBothInferred = Dirichlet(tensor([alphas[0], (alphas[1] + alphas[3]), (alphas[2] + alphas[3]), (alphas[1] + alphas[2] + alphas[3])]) * pds).sample([10_000]).mean(0)


In [ ]:
print(f"\n\nresults for rrs: {rrsSimRun}, pis: {pisSimRun}")
print("Inferred pis:", inferredPis)
print("\nP(D|V) true ans in component 1:", c1true)
print("P(D|V) inferred in component 1:", c1inferred)
print("\nP(D|V) true ans in component 1:", c2true)
print("P(D|V) inferred in component both:", c2inferred)
print("\nP(D|V) true ans in component both:", cBothTrue)
print("P(D|V) inferred in component both:", cBothInferred,"\n\n")

In [ ]:


#https://github.com/zachjennings/truncMVN/blob/master/truncMVN.pyimport numpy as np
import scipy.stats as stats
from scipy.stats import mvn

class truncMVN(object):
    """
    Class to calculate PDF of a 2D truncated multivariate normal distribution.
    
    Uses method of Alan Genz to calculate MVN CDF, implemented in scipy.
    
    low_int_limit: lower limit for *integration* of the CDFs. This is different than the lower
    limit of the bound we want to normalize! Setting to a value several SDs lower than mean should be fine.
    
    low: lower limit for the bound that we want to normalize over. Again, different from the
    lower integration limit!
    
    high: upper limit for the bound that we want to normalize over
    
    calc_norm: If true, calculate normalization at initialization. 
    """
    def __init__(self, mean=None,cov=None,low=None,high=None,re_norm=True,low_int_limit=np.array([-10.,-10.]),calc_norm=False):                    
        self.low_int_limit = low_int_limit
        self.low = low
        self.high = high
        self.re_norm = re_norm
        
        if calc_norm:
            self.norm = self.normalize(mean,cov,high,low)
            
    
    def normalize(self,mean=None,cov=None,low=None,high=None):
        """
        Calculate normalization term for the truncated MVN.
        
        Involves calculation of four CDF terms:
        P(4) - P(3) - P(2) + P(1)
        """
        #calculate CDF of full region
        cdf_4,i = mvn.mvnun(self.low_int_limit,high,mean,cov)
        
        #calculate CDFs of outside regions
        cdf_3,i = mvn.mvnun(self.low_int_limit,np.array([high[0],low[1]]),mean,cov)
        cdf_2,i = mvn.mvnun(self.low_int_limit,np.array([low[0],high[1]]),mean,cov)
        
        #calculate CDF of lower-left corner region
        cdf_1,i = mvn.mvnun(self.low_int_limit,low,mean,cov)
        
        reg_prob = (cdf_4 - cdf_3 - cdf_2 + cdf_1)
                
        return 1./reg_prob
            
        
    def logpdf(self,data,mean=np.array([]),cov=np.array([]),re_norm=True,approx=False):
        """
        Calculate the logpdf for a truncated MVN
        
        data = 2 x n array containing data to calc PDFs for.
        mean: 2 x 1 array value for MVN mean
        cov:  2x2 covariance matrix
        
        re_norm: if true, re-calculate normalization of the pdf
        
        approx: if sigmas are small, normalization is very
        close to 1 and might throw errors, so just skip. 
        """
        lpdf = stats.multivariate_normal.logpdf(data,mean=mean,cov=cov)
        
        
        if re_norm:
            #if the covaraince terms are really small, re-normalization
            #seems to throw NaNs and we probably don't need to anyway.
            #could be dangerous.
            if ((cov[0,0] < 1e-3) or (cov[1,1] < 1e-3)) and approx:
                norm = 1.
                
            else:
                norm = self.normalize(mean,cov,self.low,self.high)
        else:
            norm = self.norm
            
        return np.log(norm) + lpdf
        
        
    def pdf(self,data,mean=np.array([]),cov=np.array([]),re_norm=True):
        """
        Calculate the pdf for a truncated MVN
        
        data = 2 x n array containing data to calc PDFs for.
        mean: 2 x 1 array value for MVN mean
        cov:  2x2 covariance matrix
        """
        pdf = stats.multivariate_normal.logpdf(data,mean=mean,cov=cov)
        
        if re_norm:
            norm = self.normalize(mean,cov,self.low,self.high)
        else:
            norm = self.norm
            
        return norm * pdf

In [ ]:
# def __init__(self, mean=None,cov=None,low=None,high=None,re_norm=True,low_int_limit=np.array([-10.,-10.]),calc_norm=False):  
x = truncMVN(mean=[1.5,2], cov=[[1,1],[1,1]], low=1)

In [ ]:
x.pdf()

In [316]:
!pip install pyper

  Created wheel for pyper: filename=PypeR-1.1.2-py3-none-any.whl size=11268 sha256=4d5802adac9f268d6012e688a0ae7fa37d7f8b79ea49dd384ad2982afa437758
  Stored in directory: /Users/alexkotlar/Library/Caches/pip/wheels/6a/5c/2c/b525230bf0acc367f94ca31c3d98aa38f453a07223fbc788a8
Successfully built pyper


In [334]:
from pyper import *
import pandas as pd
r=R(use_pandas=True)
x = 10
r(f'''
    library(tmvtnorm)
    sigma <- matrix(c(4,2,2,3), ncol=2)
    x <- rtmvnorm(n=500, mean=c({x},2), sigma=sigma, lower=c(1,1))

         ''')
out = pd.DataFrame(r.get('x'))
print(out.head(5))



           0         1
0  11.851355  3.914554
1   9.604210  1.531117
2  13.059306  2.129262
3   9.686183  2.281915
4  10.544949  3.627168


In [329]:
t = r.get('x')

In [333]:
np.corrcoef(t[:,1], t[:,0])

array([[1.        , 0.42407528],
       [0.42407528, 1.        ]])

In [335]:
nGenes = 20_000
rrMeans = [5, 5, 2]

r=R(use_pandas=True)
r(f'''
    library(tmvtnorm)
    sigma <- matrix(c(1,.7,.7, .7, 1, .7 , .7, .7, 1), ncol=3)
    x <- rtmvnorm(n={nGenes}, mean=c({rrMeans[0] + rrMeans[2]}, {rrMeans[1] + rrMeans[2]}, {rrMeans[0] + rrMeans[1] + rrMeans[2]}), sigma=sigma, lower=c(1,1,1))
  ''')
rrsShared = tensor(r.get('x'))

In [338]:
np.corrcoef(rrsShared[:, 0], rrsShared[:, 1])

array([[1.        , 0.69978293],
       [0.69978293, 1.        ]])

In [339]:
rrsShared.mean(0)

tensor([ 7.0052,  7.0020, 12.0014], dtype=torch.float64)

In [347]:
r(f'''
    library(tmvtnorm)
    sigma <- matrix(c(1,.7,.7, .7, 1, .7 , .7, .7, 1), ncol=3)
    rrsShared <- rtmvnorm(n={nGenes}, mean=c({rrMeans[0] + rrMeans[2]}, {rrMeans[1] + rrMeans[2]}, {rrMeans[0] + rrMeans[1] + rrMeans[2]}), sigma=sigma, lower=c(1,1,1))
    sigma <- matrix(c(1, 0, 0, 1), ncol=2)
    rrsOne <- rtmvnorm(n={nGenes}, mean=c({rrMeans[0]}, {rrMeans[1]}), sigma=sigma, lower=c(1,1))
  ''')
rrsShared = tensor(r.get('rrsShared'))
rrsOne = tensor(r.get('rrsOne'))
print(rrsShared)
print(rrsOne)

tensor([[ 6.5747,  5.0169, 11.5317],
        [ 9.3174,  8.2048, 12.8711],
        [ 6.7278,  5.3465, 11.7076],
        ...,
        [ 6.4923,  5.5736, 11.8726],
        [ 6.3579,  7.0421, 10.4092],
        [ 8.8812,  9.1703, 13.1311]], dtype=torch.float64)
tensor([[3.4565, 4.8227],
        [3.5324, 5.2254],
        [5.0791, 4.6884],
        ...,
        [5.4115, 4.7791],
        [4.3682, 4.8309],
        [7.8831, 5.0392]], dtype=torch.float64)


In [344]:
r(f'''
    sigma <- matrix(c(1, 0, 0, 1), ncol=2)
    rr2 <- rtmvnorm(n={nGenes}, mean=c({rrMeans[0]}, {rrMeans[1]}), sigma=sigma, lower=c(1,1,1))
  ''')
rrsOne = tensor(r.get('rr2'))
# rrsOne = tensor(r.get('rrsOne'))
print(rrsOne)

RuntimeError: Could not infer dtype of NoneType