In [4]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
from mvl2 import genData2 as genData
from torch import tensor

In [7]:
simParams = genData.genParams(pis=tensor([.1, .1, .05]), rrMeans=tensor([5., 2.]), afMean = tensor(1e-4), pDs = tensor([.01, .01]), afShape=tensor(50.), nCases=tensor([1.5e4, 1.5e4, 4e3]), nCtrls=tensor(5e4), covShared=tensor([ [1, .95], [.95, 1] ]), meanEffectCovarianceScale=tensor(.01))[0]
simParams["pDs"] = simParams["pDs"][0:2]
sim1 = genData.v6liability(**simParams)


PD1 threshold, PD2 threshold tensor(-2.3263) tensor(-2.3263)
pDsWithBoth tensor([0.0100, 0.0100, 0.0067], dtype=torch.float64)
pdThresh tensor([2.3263, 2.3263])
pdTarget tensor([0.0500, 0.0200])
pdvthresh tensor([1.6449, 2.0537])
meanEffect tensor([0.6815, 0.2726])
meanEffectsAcrossAllGenes tensor([0.6815, 0.2726])
allEffects tensor([[-0.5716, -0.2140],
        [-0.7963, -0.4323],
        [-0.6585, -0.2169],
        ...,
        [-0.4951, -0.1161],
        [-0.6276, -0.2512],
        [-0.6355, -0.2662]])
allEffects[i] tensor([-0.5716, -0.2140])
PDBothGivenV.mean tensor(0.0194, dtype=torch.float64)
PDBothGivenV / PDBoth tensor(2.8987, dtype=torch.float64)
pdsCovarOnMean.mean(0) tensor([0.0508, 0.0205, 0.0194], dtype=torch.float64)
np.corrcoef(pdvInBoth[:,0], pdvInBoth[:,1])
 [[1.         0.94873839]
 [0.94873839 1.        ]]
np.corrcoef(pdvInBoth[:,0], pdvInBoth[:,2])
 [[1.         0.96079169]
 [0.96079169 1.        ]]
PDBoth1GivenV tensor([0.0415, 0.0241, 0.0234,  ..., 0.0385, 0.0375, 

In [10]:
sim2 = genData.v6liability2(**simParams)

PD1 threshold, PD2 threshold tensor(-2.3263) tensor(-2.3263)
pDsWithBoth tensor([0.0100, 0.0100, 0.0067], dtype=torch.float64)
pdThresh tensor([2.3263, 2.3263])
pdTarget tensor([0.0500, 0.0200])
pdvthresh tensor([1.6449, 2.0537])
meanEffect tensor([0.6815, 0.2726])
meanEffectsAcrossAllGenes tensor([0.6815, 0.2726])
allEffects tensor([[-0.6565, -0.2722],
        [-0.7032, -0.3167],
        [-0.5909, -0.1706],
        ...,
        [-0.7976, -0.3954],
        [-0.6598, -0.2527],
        [-0.7704, -0.3520]])
allEffects[i] tensor([-0.6565, -0.2722])
PDBothGivenV.mean tensor(0.0194, dtype=torch.float64)
PDBothGivenV / PDBoth tensor(2.9027, dtype=torch.float64)
pdsCovarOnMean.mean(0) tensor([0.0508, 0.0205, 0.0194], dtype=torch.float64)
np.corrcoef(pdvInBoth[:,0], pdvInBoth[:,1])
 [[1.         0.94922391]
 [0.94922391 1.        ]]
np.corrcoef(pdvInBoth[:,0], pdvInBoth[:,2])
 [[1.         0.96124813]
 [0.96124813 1.        ]]
PDBoth1GivenV tensor([0.0007, 0.0006, 0.0006,  ..., 0.0006, 0.0004, 

In [11]:
sim2 = genData.v6liability2(**simParams)

PD1 threshold, PD2 threshold tensor(-2.3263) tensor(-2.3263)
pDsWithBoth tensor([0.0100, 0.0100, 0.0067], dtype=torch.float64)
pdThresh tensor([2.3263, 2.3263])
pdTarget tensor([0.0500, 0.0200])
pdvthresh tensor([1.6449, 2.0537])
meanEffect tensor([0.6815, 0.2726])
meanEffectsAcrossAllGenes tensor([0.6815, 0.2726])
allEffects tensor([[-0.6556, -0.2824],
        [-0.6386, -0.2399],
        [-0.9835, -0.5467],
        ...,
        [-0.6359, -0.2535],
        [-0.6975, -0.3003],
        [-0.7697, -0.3424]])
allEffects[i] tensor([-0.6556, -0.2824])
PDBothGivenV.mean tensor(0.0195, dtype=torch.float64)
PDBothGivenV / PDBoth tensor(2.9073, dtype=torch.float64)
pdsCovarOnMean.mean(0) tensor([0.0509, 0.0205, 0.0195], dtype=torch.float64)
np.corrcoef(pdvInBoth[:,0], pdvInBoth[:,1])
 [[1.         0.94852359]
 [0.94852359 1.        ]]
np.corrcoef(pdvInBoth[:,0], pdvInBoth[:,2])
 [[1.         0.96060976]
 [0.96060976 1.        ]]
PDBoth1GivenV tensor([0.0099, 0.0098, 0.0100,  ..., 0.0098, 0.0099, 

In [ ]:
sim2 = genData.v6liability2(**simParams)